services:
  - type: web
    name: SACAL
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    autoDeploy: true
envVars:
  - key: PYTHONPATH
    value: .
